# MailingGroup  by Ferius_057 aka Charles_Grozny
# Разработчик: vk.com/ferius_057
# Исходный код: github.com/Ferius057/VK-MailingGroup


# Токен группы
token: 'token'


# Тестовая рассылка
testMode:
  # true = будет отправлено только пользователям из списка 'users'
  # false = полноценная рассылка всем пользователям с кем был диалог
  enable: false
  # просто id пользователя(только цифры, id в начале не нужен)
  users:
    - 1
    - 621876211



# Список id пользователей которые не будут получать рассылку
# просто id пользователя(только цифры, id в начале не нужен)
blackList:
  - 271921577



# Максимум вложений в 1 сообщений = 10,
# в ином случае будет добавлены только первые написанные
## Не нужные вложения оставьте строку пустым
## Пример:
##  photo:
##    - ''
##  wall:
##    - ''
attachments:
  # В 1 сообщений можно прикреплять 10 фотографий.
  photo:
    - '1.jpg'
    - '2.jpg'
    - '3.jpg'

  # В 1 сообщений можно прикрепить только 1 пост.
  # Подробную информацию про то как добавить запись: https://github.com/Ferius057/VK-MailingGroup/blob/master/docs/wall.md
  wall:
    - 'wall-200934694_40'



# Текст сообщения который будет отправлен.
# Важно что бы до текста(после "message: |") на каждой строке был отступ в 2 пробела
message: |
  Привет.
  Тест рассылки.
