# MailingGroup  by Ferius_057 aka Charles_Grozny
# Разработчик: vk.com/ferius_057
# Исходный код: github.com/Ferius057/VK-MailingGroup


# Токен группы
token: 'token'


# Тестовая рассылка
testMode:
  # true = будет отправлено только пользователям из списка 'users'
  # false = полноценная рассылка всем пользователям с кем был диалог
  enable: true
  users:
    - 1
    - 621876211



  # Максимум вложений в 1 сообщений = 10,
  # в ином случае будет добавлены только первые написанные
## Не нужные вложения оставьте строку пустым
## Пример:
##  photo:
##    - ''
##  wall:
##    - ''
attachments:
  # В 1 сообщений можно прикреплять 10 фотографий.
  photo:
    - '1.jpg'
    - '2.jpg'
    - '3.jpg'

  # В 1 сообщений можно прикреплять только 1 пост.
  wall:
    - 'wall-200934694_40'



# Текст сообщения который будет отправлен.
message:
  - 'Привет.'
  - 'Тест рассылки.'