# Разработчик: https://vk.com/ferius_057

# Токен группы
token: 'token'


# Тестовая рассылка
testMode:
  # true = будет отправлено только пользователям из списка 'users'
  # false = полноценная рассылка всем пользователям с кем был диалог
  enable: false
  users:
    - 615081290
    - 1
    - 2
    - 621876211



  # Максимум вложений в 1 сообщений = 10,
  # в ином случае будет добавлены только первые написанные
## Не нужные вложения оставьте строку пустым
## Пример:
##  photo:
##    - ''
##  wall:
##    - ''
attachments:
  # В 1 сообщений можно прикреплять 10 фотографий.
  photo:
    - 'img.png'
    - '1.jpg'
    - '2.jpg'
    - '2.jpg'
    - '3.jpg'

  # В 1 сообщений можно прикреплять только 1 пост.
  wall:
    - 'wall-28905875_30158949'



# Текст сообщения который будет отправлен.
message:
  - 'Привет.'
  - 'Тест рассылки.'