# Разработчик: https://vk.com/ferius_057

# Токен группы
token: 'token'



# Максимум вложений в 1 сообщений = 10,
  # в ином случае будет добавлены только первые написанные
# Не нужные вложения добавляйте в комментарий через #
attachments:
  # В 1 сообщений можно прикреплять 10 фотографий.
  photo:
    - '1.jpg'
    - '2.jpg'
    - '3.jpg'
    - '4.jpg'
    - '5.jpg'
    - '6.jpg'
    - '7.jpg'
    - '8.png'

  # В 1 сообщений можно прикреплять только 1 пост.
  wall:
    - 'wall621876211_164'



# Текст сообщения который будет отправлен.
message:
  - 'Привет.'
  - 'Тест рассылки.'